### PR TITLE
Current pantry ingredient search page

### PR DESCRIPTION
**Pull request by JHCuc3m**
Captura de pantalla 2024-11-25 145738

### CODE REVIEW

**Review by just1ntime — DISMISSED** [review]
solid changes!

**Review by just1ntime — APPROVED** [review]
approved

**Review by just1ntime — APPROVED** [review]
looks good

**Review by nickGraham0 — APPROVED** [review]
Looks good

**Review by ikhyunAn — DISMISSED** [review]
should be good to merge

**Review by ikhyunAn — DISMISSED** [review]
2nd try

**Comment by JHCuc3m** [comment]
closed

**Pull request closed without merging**
